window.PMEGP_CANDIDATE_DATA = {
  "name:ishwar kumar nag": {
    "loan": 3000000,
    "udyam": "NO",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "NO",
    "remark": "Incomplete",
    "updates": "Call Not Received"
  },
  "mob:8815795087": {
    "loan": 3000000,
    "udyam": "NO",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "NO",
    "remark": "Incomplete",
    "updates": "Call Not Received"
  },
  "name:gabraiel": {
    "loan": 1000000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "mob:9131871400": {
    "loan": 1000000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "name:pappu thakur": {
    "loan": 400000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "mob:9752724222": {
    "loan": 400000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "name:sunil telam": {
    "loan": 1000000,
    "udyam": "NO",
    "bank": "",
    "pan": "",
    "adhar": "",
    "voter": "",
    "quotation": "",
    "remark": "RANG DE",
    "updates": "Done"
  },
  "mob:9926344668": {
    "loan": 1000000,
    "udyam": "NO",
    "bank": "",
    "pan": "",
    "adhar": "",
    "voter": "",
    "quotation": "",
    "remark": "RANG DE",
    "updates": "Done"
  },
  "name:rohit kumar": {
    "loan": "3,00,000",
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "complete",
    "updates": "ON Way DIC"
  },
  "mob:8770839584": {
    "loan": "3,00,000",
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "complete",
    "updates": "ON Way DIC"
  },
  "name:vijay kartam": {
    "loan": 1000000,
    "udyam": "",
    "bank": "",
    "pan": "",
    "adhar": "",
    "voter": "",
    "quotation": "",
    "remark": "Incomplete",
    "updates": "Phone Switched Off"
  },
  "mob:9691730048": {
    "loan": 1000000,
    "udyam": "",
    "bank": "",
    "pan": "",
    "adhar": "",
    "voter": "",
    "quotation": "",
    "remark": "Incomplete",
    "updates": "Phone Switched Off"
  },
  "name:narendra kumar jurri": {
    "loan": 1200000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "mob:6267846621": {
    "loan": 1200000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "name:maharu ram": {
    "loan": 470000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO GRAMODHYOG",
    "updates": "Done"
  },
  "mob:6264459312": {
    "loan": "",
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "name:sarvesh punem": {
    "loan": 500000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "Incomplete",
    "updates": "Call Not Received"
  },
  "mob:9238914122": {
    "loan": 500000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "Incomplete",
    "updates": "Call Not Received"
  },
  "name:ratan poyam": {
    "loan": 1000000,
    "udyam": "",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "NO",
    "remark": "Incomplete",
    "updates": "Lined up & Not Serious"
  },
  "mob:7587848771": {
    "loan": 1000000,
    "udyam": "",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "NO",
    "remark": "Incomplete",
    "updates": "Lined up & Not Serious"
  },
  "name:golu markam": {
    "loan": 1500000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO GRAMODHYOG",
    "updates": "Done"
  },
  "mob:6266068909": {
    "loan": 1500000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO GRAMODHYOG",
    "updates": "Done"
  },
  "name:sukhmati kudami": {
    "loan": 250000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "mob:7647002405": {
    "loan": 250000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "name:dinu kadti": {
    "loan": 400000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO GRAMODHYOG",
    "updates": "Done"
  },
  "mob:7587314392": {
    "loan": 400000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO GRAMODHYOG",
    "updates": "Done"
  },
  "name:santosh korram": {
    "loan": 200000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "complete",
    "updates": "Lined up & Not Serious"
  },
  "mob:9301768898": {
    "loan": 200000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "complete",
    "updates": "Lined up & Not Serious"
  },
  "name:masa": {
    "loan": 1000000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "",
    "remark": "Incomplete",
    "updates": "Dont Want "
  },
  "mob:7725836882": {
    "loan": 1000000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "",
    "remark": "Incomplete",
    "updates": "Dont Want "
  },
  "name:rita markam": {
    "loan": 1300000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "mob:7489511406": {
    "loan": 1300000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "name:akshay tati": {
    "loan": 1200000,
    "udyam": "NO",
    "bank": "",
    "pan": "",
    "adhar": "",
    "voter": "",
    "quotation": "",
    "remark": "",
    "updates": "Lined up & Serious"
  },
  "mob:7433057562": {
    "loan": 1200000,
    "udyam": "NO",
    "bank": "",
    "pan": "",
    "adhar": "",
    "voter": "",
    "quotation": "",
    "remark": "",
    "updates": "Lined up & Serious"
  },
  "name:joga ram barse": {
    "loan": 1500000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "mob:7879327232": {
    "loan": 1500000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "mob:9329286068": {
    "loan": 1000000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "name:mintu kashyap": {
    "loan": 1000000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "complete",
    "updates": "Dont Want "
  },
  "mob:6264028279": {
    "loan": 1000000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "complete",
    "updates": "Dont Want "
  },
  "name:raju kadti": {
    "loan": 200000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO GRAMODHYOG",
    "updates": "Done"
  },
  "mob:6268270286": {
    "loan": 200000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO GRAMODHYOG",
    "updates": "Done"
  },
  "name:somaru kadti": {
    "loan": 1500000,
    "udyam": "NO",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "NO",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "mob:7647069733": {
    "loan": 1500000,
    "udyam": "NO",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "NO",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "name:kama ram": {
    "loan": 1000000,
    "udyam": "NO",
    "bank": "",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "NO",
    "remark": "Incomplete",
    "updates": "Lined up & Not Serious"
  },
  "mob:7999315122": {
    "loan": 1000000,
    "udyam": "NO",
    "bank": "",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "NO",
    "remark": "Incomplete",
    "updates": "Lined up & Not Serious"
  },
  "name:sonu muchaki": {
    "loan": 500000,
    "udyam": "NO",
    "bank": "",
    "pan": "",
    "adhar": "",
    "voter": "",
    "quotation": "",
    "remark": "Incomplete",
    "updates": "Lined up & Not Serious"
  },
  "mob:7587214758": {
    "loan": 500000,
    "udyam": "NO",
    "bank": "",
    "pan": "",
    "adhar": "",
    "voter": "",
    "quotation": "",
    "remark": "Incomplete",
    "updates": "Lined up & Not Serious"
  },
  "name:shashi telam": {
    "loan": 1300000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "mob:6264581969": {
    "loan": 1300000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "name:manku telam": {
    "loan": 30000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": 32,
    "remark": "complete",
    "updates": "Lined up & Serious"
  },
  "mob:9770958183": {
    "loan": 30000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": 32,
    "remark": "complete",
    "updates": "Lined up & Serious"
  },
  "name:suresh karma": {
    "loan": 1000000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "mob:930232336": {
    "loan": 250000,
    "udyam": "",
    "bank": "",
    "pan": "",
    "adhar": "",
    "voter": "",
    "quotation": "",
    "remark": "Incomplete",
    "updates": "Can Not Reachable"
  },
  "mob:6266418652": {
    "loan": 1000000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "name:praveen kumar barse": {
    "loan": 100000,
    "udyam": "NO",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "NO",
    "remark": "Incomplete",
    "updates": "Not Intrested"
  },
  "mob:6262338085": {
    "loan": 100000,
    "udyam": "NO",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "NO",
    "remark": "Incomplete",
    "updates": "Not Intrested"
  },
  "name:guddi bhaskar": {
    "loan": 50000,
    "udyam": "",
    "bank": "",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "NO",
    "remark": "Incomplete",
    "updates": "Not Intrested"
  },
  "mob:7067481024": {
    "loan": 50000,
    "udyam": "",
    "bank": "",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "NO",
    "remark": "Incomplete",
    "updates": "Not Intrested"
  },
  "name:laxmi gupta": {
    "loan": 40000,
    "udyam": "YES",
    "bank": "",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "NO",
    "remark": "Incomplete",
    "updates": "Something Error"
  },
  "mob:9238872458": {
    "loan": 40000,
    "udyam": "YES",
    "bank": "",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "NO",
    "remark": "Incomplete",
    "updates": "Something Error"
  },
  "name:ritesh markam": {
    "loan": 300000,
    "udyam": "NO",
    "bank": "",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "NO",
    "remark": "Incomplete",
    "updates": "Not Sure & Confused"
  },
  "mob:7805889744": {
    "loan": 300000,
    "udyam": "NO",
    "bank": "",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "NO",
    "remark": "Incomplete",
    "updates": "Not Sure & Confused"
  },
  "name:nikita karma": {
    "loan": "",
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "mob:7489301928": {
    "loan": "",
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "name:pilu ram kashyap": {
    "loan": "",
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "mob:7828138393": {
    "loan": "",
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO DIC",
    "updates": "Done"
  },
  "mob:6464459312": {
    "loan": 470000,
    "udyam": "YES",
    "bank": "YES",
    "pan": "YES",
    "adhar": "YES",
    "voter": "YES",
    "quotation": "YES",
    "remark": "SEND TO GRAMODHYOG",
    "updates": "Done"
  }
};
